version: '3'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    volumes:
      - .:/var/www
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    platform: linux/x86_64
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    volumes:
      - laravel_mysql:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
      dockerfile: ./Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  laravel_mysql:
    driver: local
